site_name: Zoe's Notes
site_url: https://zoedrift.github.io/notebook/
repo_url: https://github.com/zoedrift/notebook
repo_name: ""
site_author: Zoe

nav:
  - é¦–é¡µ: index.md
  - è¯¾ç¨‹ç¬”è®°:
      - gis:
          - gisç›¸å…³: blog/gis/gisnote.md
      - å¤§ä¸€:
          - Cç¨‹åºè®¾è®¡åŸºç¡€åŠå®éªŒ: 
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/c/cnote.md
          - äººå·¥æ™ºèƒ½åŸºç¡€(A): 
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/AIaNote/è¯¾ç¨‹ä¿¡æ¯.md
              - æœŸæœ«å¤ä¹ ç¬”è®°: 
                  - ç¬¬ä¸€ç¯‡: blog/year1/AIaNote/ä¸€.md
                  - ç¬¬äºŒç¯‡: blog/year1/AIaNote/äºŒ.md
                  - ç¬¬ä¸‰ç¯‡: blog/year1/AIaNote/ä¸‰.md
                  - ç¬¬å››ç¯‡: blog/year1/AIaNote/å››.md
              - å°æµ‹: blog/year1/AIaNote/å°æµ‹.md
          - PythonåŸºç¡€: 
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/PythonNote/è¯¾ç¨‹ä¿¡æ¯.md
              - çŸ¥è¯†ç‚¹: blog/year1/PythonNote/çŸ¥è¯†ç‚¹.md
              - ç†è®ºé¢˜: blog/year1/PythonNote/error.md
              - ç¼–ç¨‹é¢˜: blog/year1/PythonNote/code.md
              - æ–‡ä»¶: blog/year1/PythonNote/file.md
              - oop: blog/year1/PythonNote/oop.md
          - åœ°çƒç§‘å­¦å¯¼è®º: 
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/åœ°çƒç§‘å­¦å¯¼è®º/è¯¾ç¨‹ä¿¡æ¯.md
              - ç¬”è®°: blog/year1/åœ°çƒç§‘å­¦å¯¼è®º/dkdnote/é‡ç‚¹.md
          - åœ°ç†ä¿¡æ¯ç§‘å­¦å¯¼è®º: 
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/gis_intro/classimformation.md
              - æ¢—æ¦‚: blog/year1/gis_intro/gisnote.md
              - å®éªŒç¬”è®°: blog/year1/gis_intro/labnote.md
          - è‡ªç„¶åœ°ç†å­¦: 
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/è‡ªç„¶åœ°ç†note/è¯¾ç¨‹ä¿¡æ¯.md
              - æ—èˆŸ: blog/year1/è‡ªç„¶åœ°ç†note/æ—èˆŸ.md
              - åœŸå£¤: blog/year1/è‡ªç„¶åœ°ç†note/åœŸå£¤.md
              - ç”Ÿç‰©: blog/year1/è‡ªç„¶åœ°ç†note/ç¬¬ä¸ƒç« ï¼ˆç”Ÿç‰©ï¼‰.md
              - å†å¹´å·: blog/year1/è‡ªç„¶åœ°ç†note/å†å¹´1.md
          - åœ°ç†è®¤çŸ¥å®ä¹ :
              - è¯¾ç¨‹ä¿¡æ¯: blog/year1/åœ°ç†è®¤çŸ¥å®ä¹ /è¯¾ç¨‹ä¿¡æ¯.md
              - è¥¿åŒ—å¹²æ—±åŠå¹²æ—±åŒºåœ°ç†: blog/year1/åœ°ç†è®¤çŸ¥å®ä¹ /1.md
              - ä¸­å›½å¹²æ—±åŠå¹²æ—±åœ°åŒºè‡ªç„¶åœ°ç†è®¤çŸ¥å®ä¹ --åŒ—å¤©å±±ä¸å‡†å™¶å°”ç›†åœ°: blog/year1/åœ°ç†è®¤çŸ¥å®ä¹ /fx.md
          
          #- å¾®ç§¯åˆ†: year1/calculus.md
      - å¤§äºŒ:
          - é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/oop/å‰è¨€.md
          - æ¦‚ç‡è®ºä¸æ•°ç†ç»Ÿè®¡:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/æ¦‚ç»Ÿ/å‰è¨€.md
          - åœ°å›¾å­¦:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/åœ°å›¾å­¦/è¯¾ç¨‹ä¿¡æ¯.md
          - äººæ–‡åœ°ç†å­¦:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/äººæ–‡åœ°ç†/è¯¾ç¨‹ä¿¡æ¯.md
          - ç°ä»£æ°”å€™å­¦åŸºç¡€:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/ç°ä»£æ°”å€™å­¦åŸºç¡€/è¯¾ç¨‹ä¿¡æ¯.md
          - å¤§å­¦ç‰©ç†(ä¹™):
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/physics/è¯¾ç¨‹ä¿¡æ¯.md
          - å¤§å­¦ç‰©ç†å®éªŒ:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/phylab/è¯¾ç¨‹ä¿¡æ¯.md
          - é©¬å…‹æ€ä¸»ä¹‰åŸºæœ¬åŸç†:
              - è¯¾ç¨‹ä¿¡æ¯: blog/year2/é©¬åŸ/è¯¾ç¨‹ä¿¡æ¯.md
          #- æœºå™¨å­¦ä¹ : year2/ml.md
  - cs:
      - ä¸€äº›æœ‰ç”¨çš„èµ„æ–™: blog/computerscience/cs.md
  - å®ç”¨å·¥å…·: 
      - latex: blog/tool/latex.md
      - markdown: blog/tool/markdown.md
      - git: blog/tool/git.md

      - mkdocs: blog/tool/mkdocs.md
      - webå¼€å‘: 
          - htmlã€cssã€js: blog/tool/webå¼€å‘/ä¸‰ä»¶å¥—.md
          - vue: blog/tool/webå¼€å‘/vue.md

  - æ‚é¡¹:
      - æ¢¦åˆ°å“ªå¥è¯´å“ªå¥:
          - æŠ¹èŒ¶: blog/sundries/dream/tea.md
      - åˆ«çœ‹: blog/sundries/bz.md
      - çŒå¥‡: blog/sundries/rubbish.md
  

theme:
  name: material
  language: zh

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss #å‘ˆç°å¯æ ‡è®°ä¸ºç”±ç”¨æˆ·è¯»å–çš„ä¸´æ—¶å…¬å‘Šï¼Œå¯ä»¥åŒ…å«ä¸€ä¸ªç”¨äºå–æ¶ˆå½“å‰å…¬å‘Šçš„æŒ‰é’®
    # - navigation.instant
    #- header.autohide  #è‡ªåŠ¨éšè—
    - navigation.tracking #åœ°å€æ ä¸­çš„ URL å°†è‡ªåŠ¨æ›´æ–°ä¸ºåœ¨ç›®å½•ä¸­çªå‡ºæ˜¾ç¤ºçš„æ´»åŠ¨é”šç‚¹
    - navigation.tabs #é¡¶çº§éƒ¨åˆ†å°†å‘ˆç°åœ¨ä¸Šé¢è§†å£æ ‡é¢˜ä¸‹æ–¹çš„èœå•å±‚ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    # - navigation.tabs.sticky  #å¯ç”¨ç²˜æ€§é€‰é¡¹å¡åï¼Œå¯¼èˆªé€‰é¡¹å¡å°†é”å®šåœ¨æ ‡é¢˜ä¸‹æ–¹ï¼Œå¹¶åœ¨å‘ä¸‹æ»šåŠ¨æ—¶å§‹ç»ˆä¿æŒå¯è§
    - navigation.sections #å¯ç”¨éƒ¨åˆ†åï¼Œé¡¶çº§éƒ¨åˆ†åœ¨è¾¹æ ä¸­å‘ˆç°ä¸º1220pxä»¥ä¸Šè§†å£çš„ç»„ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.footer #é¡µè„šå°†å‘ˆç°åœ¨è¾¹æ ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - search.share #æœç´¢åˆ†äº«æŒ‰é’®
    - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - navigation.indexes #å¯ç”¨èŠ‚ç´¢å¼•é¡µåï¼Œå¯ä»¥å°†æ–‡æ¡£ç›´æ¥é™„åŠ åˆ°èŠ‚
    - content.tabs.link
    - content.tooltips
    - content.code.copy #ä»£ç å¤åˆ¶
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    
  icon:
    repo: fontawesome/brands/github #å³ä¸Šè§’å›¾æ ‡

  logo: assets/images/logo.PNG

extra_css:
  - extra.css

extra:
  generator: false # é¡µè„šä¸æ˜¾ç¤ºmade by...

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZoeDrift

    - icon: fontawesome/regular/envelope
      link: mailto:<2991146639@qq.com>

  math: true

plugins:
  - search #æœç´¢é…ç½®
  # - git-committers:
  #     enabled: !ENV [git-committers, true]
  #     repository: ZoeDrift/notebook
  #     branch: main
  #     exclude:
  #       - index.md
  #       - tag.md
  #       - liuyanban.md
  #       - blog/posts/update.md
  #       - blog/posts/wkw.md
  #       - about/link.md
  - git-revision-date-localized:
      enabled: !ENV [git-revision-date-localized, false]
      type: iso_date
      enable_creation_date: false
      exclude:
        - index.md
        - tag.md
        - liuyanban.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
        - websitebeauty/linktech.md
  #- blog: #åšå®¢é…ç½®
      #post_date_format: full #æ—¶é—´
      #draft: true
      #draft_if_future_date: true #è‡ªåŠ¨å°†å…·æœ‰æœªæ¥æ—¥æœŸçš„å¸–å­æ ‡è®°ä¸ºè‰ç¨¿
      #post_readtime: true
      #post_readtime_words_per_minute: 265 #è®¡ç®—å¸–å­çš„é˜…è¯»æ—¶é—´æ—¶è¯»è€…æ¯åˆ†é’Ÿé¢„è®¡é˜…è¯»çš„å­—æ•°
      #post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      #pagination_url_format: "page/{page}"
      #authors_file: "{blog}/.authors.yml" #ä½œè€…ä¿¡æ¯
  #- tags

markdown_extensions: #è¯¦è§https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ å’Œ https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # ä»£ç å—é«˜äº®æ’ä»¶
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      linenums: true # æ˜¾ç¤ºè¡Œå·
      auto_title: false # true-æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latexæ”¯æŒ
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latexæ”¯æŒ

site_name: æˆ‘çš„ç¬”è®°

plugins:
  - search
  - encryptcontent:
      global_password: null
      title_prefix: "ğŸ”"
      summary: "å‰é¢çš„åŒºåŸŸä»¥åå†æ¥æ¢ç´¢å§"
      placeholder: "è¯·è¾“å…¥å¯†ç ğŸ”‘"
      encryption_failure_message: "å†™å¥½äº†å†å‘"
      decryption_failure_message: "å¯†ç é”™è¯¯ï¼Œè¯·å†è¯•ä¸€æ¬¡ï¼"
      password_button: true